export type PostSolarMicroServices = {
  wavelength: number;
  sam_type: string;
  custom_sam_ri?: number;
  custom_sam_k?: number;
  sam_thickness: number;
  substrate_type: string;
  custom_substrate_ri?: number;
  custom_substrate_k?: number;
  substrate_thickness: number;
  electrode_type: string;
  custom_electrode_ri?: number;
  custom_electrode_k?: number;
  electrode_thickness: number;
  photoanode_thickness: number;
  custom_photoanode_ri?: number;
  custom_photoanode_k?: number;
  dye_thickness: number;
  custom_dye_ri?: number;
  custom_dye_k?: number;
  solar_irradiance: number;
  area: number;
  num_hours: number;
  total_plug_load: number;

  sam_ri?: number;
  sam_k?: number;
  substrate_ri?: number;
  substrate_k?: number;
  electrode_ri?: number;
  electrode_k?: number;
  photoanode_ri?: number;
  photoanode_k?: number;
  dye_ri?: number;
  dye_k?: number;
};
